SENHA_ADMIN = "admin123"
SUPABASE_URL = "https://vsbrpqxoszagpgzwbtiq.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzYnJwcXhvc3phZ3BnendidGlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUyNjU0MzMsImV4cCI6MjEwMDg0MTQzM30.jvXrSdNtiWKMQ0mDq6LEVu5Js3hnPqByDN6wj4EgWPA"